server:
  port: 8090

spring:
  application:
    name: share2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.236.129:3306/share?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: admin
